//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Calendar_With_Notes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF_Calendar_With_Notes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacje o....
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Notatkę.
        /// </summary>
        public static string AddNewNote {
            get {
                return ResourceManager.GetString("AddNewNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz godzinę.
        /// </summary>
        public static string ChooseHour {
            get {
                return ResourceManager.GetString("ChooseHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybór Dnia.
        /// </summary>
        public static string ChoosingDay {
            get {
                return ResourceManager.GetString("ChoosingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treść notatki.
        /// </summary>
        public static string ContentOfNote {
            get {
                return ResourceManager.GetString("ContentOfNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podana godzina i minuta jest już zajęta.Poprzednia notatka zostanie usunięta.Kontynuować?.
        /// </summary>
        public static string CurrentNoteBusy {
            get {
                return ResourceManager.GetString("CurrentNoteBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Bazy danych: Błąd.
        /// </summary>
        public static string DataBaseStateFails {
            get {
                return ResourceManager.GetString("DataBaseStateFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Bazy danych: OK.
        /// </summary>
        public static string DataBaseStateOK {
            get {
                return ResourceManager.GetString("DataBaseStateOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dzień.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytowany dzień.
        /// </summary>
        public static string EditedDay {
            get {
                return ResourceManager.GetString("EditedDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj Zaznaczoną.
        /// </summary>
        public static string EditingOfNotes {
            get {
                return ResourceManager.GetString("EditingOfNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj Zaznaczoną.
        /// </summary>
        public static string EditSelected {
            get {
                return ResourceManager.GetString("EditSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakończ.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomoc.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalendarz z notatkami.Zaznacz dzień, aby dopisać lub usunąć notatki.Dodawanie notatek: Przycisk Dodaj Notatkę.Edytowanie: Przycisk Edytuj Zaznaczoną. Przyciski uaktywniają się,po zaznaczeniu notatki..
        /// </summary>
        public static string HelpInformation {
            get {
                return ResourceManager.GetString("HelpInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomoc do programu Kalendarz z Notatkami.
        /// </summary>
        public static string HelpInformationTitle {
            get {
                return ResourceManager.GetString("HelpInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godz.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Język.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalendarz z Notatkami.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;brak&gt;.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notatka.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notatka jest pusta. Zapisać?.
        /// </summary>
        public static string NoteEmpty {
            get {
                return ResourceManager.GetString("NoteEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacja o pustej notatce.
        /// </summary>
        public static string NoteEmptyTitle {
            get {
                return ResourceManager.GetString("NoteEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notatka zostanie usunięta.
        /// </summary>
        public static string NoteWillBeDeleted {
            get {
                return ResourceManager.GetString("NoteWillBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuwanie notatki.
        /// </summary>
        public static string NoteWillBeDeletedTitle {
            get {
                return ResourceManager.GetString("NoteWillBeDeletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba Notatek.
        /// </summary>
        public static string NumberOfNotes {
            get {
                return ResourceManager.GetString("NumberOfNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość notatek.
        /// </summary>
        public static string NumberOfPositionDescription {
            get {
                return ResourceManager.GetString("NumberOfPositionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcje.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikacja zostanie zamknięta. Kontynuować?.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdź zakończenie.
        /// </summary>
        public static string QuitTitle {
            get {
                return ResourceManager.GetString("QuitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń Zaznaczoną.
        /// </summary>
        public static string RemoveSelectedNote {
            get {
                return ResourceManager.GetString("RemoveSelectedNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisać nową notatkę na miejscu starej?.
        /// </summary>
        public static string ReplaceNote {
            get {
                return ResourceManager.GetString("ReplaceNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
    }
}
